uint64 timestamp	# time since system start (microseconds)
char[10] name           # max. 10 characters as key / name
float32 x               # x value
float32 y               # y value
float32 z               # z value
float32 n               # n value; yo se la agregue
float32 o               # o value; yo se la agregue
float32 p               # p value; yo se la agregue
float32 q               # q value; yo se la agregue
float32 r               # r value; yo se la agregue
float32 u               # u value; yo se la agregue
float32 v               # v value; yo se la agregue
float32 w               # w value; yo se la agregue
float32 l               # l value; yo se la agregue
float32 m               # m value; yo se la agregue
float32 k               # k value; yo se la agregue
float32 j               # j value; yo se la agregue
float32 i               # i value; yo se la agregue
